// ─────────────────────────────────────────────────────────────────────────────
// Help & How It Works — all guide content, as plain data (no Firestore reads).
//
// KEEP THIS IN STEP WITH THE APP. Whenever a screen, button label, permission or
// workflow changes, update the matching articles here in the same change. Describe
// only what the app really does — use the exact menu, button and field names.
//
// Article fields
//   id, category, title, description, when
//   requires   — who can see it: 'patients.create' (module.action from the permission
//                catalog), 'superadmin', 'adminOrAbove', or an array (all must pass)
//   audience   — optional role list for role-specific guides (e.g. ['therapist'])
//   keywords   — extra search words
//   steps      — [{ title, text, visual?, image? }]
//                visual: { nav: 'Patients' } | { button: 'Add Patient', variant, icon }
//                        | { tabs: [...], active } | { fields: [{ label, required }] }
//                        | { chips: [...], active: [...] }
//                image: optional screenshot path (e.g. '/help/add-patient-1.png') shown
//                       instead of the drawn visual — replace freely when the UI changes.
//   result, tips[], important[], related[ids], action { label, to, requires }
//   fixes      — troubleshooting only: [{ cause, solution, needsAdmin? }]
// ─────────────────────────────────────────────────────────────────────────────

export const CATEGORIES = [
  { id: 'getting-started', title: 'Getting Started', icon: 'Rocket', description: 'Signing in, finding your way around, notifications.' },
  { id: 'dashboard', title: 'Dashboard', icon: 'LayoutDashboard', description: 'What the dashboard figures mean.' },
  { id: 'patients', title: 'Patients', icon: 'ClipboardList', description: 'Register, find, update, discharge and readmit patients.' },
  { id: 'therapy', title: 'Therapy Sessions', icon: 'Activity', description: 'Recording daily treatment progress.' },
  { id: 'bills', title: 'Bills & Invoices', icon: 'FileText', description: 'Create, print, correct medical invoices.' },
  { id: 'payments', title: 'Payments & Receipts', icon: 'Wallet', description: 'Advance and later payments, receipts, dues.' },
  { id: 'ipd', title: 'IPD / Admission & Discharge', icon: 'BedDouble', description: 'Inpatient running bills, admission and discharge.' },
  { id: 'services', title: 'Services & Departments', icon: 'Building2', description: 'The service catalog and prices.' },
  { id: 'settlement', title: 'Hospital Settlement', icon: 'HandCoins', description: 'Daily hospital-covered amounts for inpatients.' },
  { id: 'inquiries', title: 'Inquiries', icon: 'Inbox', description: 'Website consultation requests, messages, job applications.' },
  { id: 'staff', title: 'Staff & Permissions', icon: 'Users', description: 'Staff accounts, roles and access.' },
  { id: 'settings', title: 'Settings', icon: 'Settings', description: 'Hospitals, therapists, tax and billing settings.' },
  { id: 'trash', title: 'Trash', icon: 'Trash2', description: 'Restoring deleted patients, bills and staff.' },
  { id: 'printing', title: 'Printing & PDF', icon: 'Printer', description: 'Printing and saving bills and receipts as PDF.' },
  { id: 'troubleshooting', title: 'Troubleshooting', icon: 'Wrench', description: 'Something not working? Start here.' },
];

export const ROLE_INTRO = {
  superadmin: 'You can see every part of the system. Guides for setting up hospitals, staff and permissions are included.',
  admin: 'Guides for patients, billing, IPD running bills, discharge and day-to-day management.',
  receptionist: 'Guides for front-desk work: registering patients, bills, payments, receipts and IPD running bills.',
  therapist: 'Guides for your patients and recording daily treatment progress.',
};

// Shown first on the Help Center home (only those the viewer can use).
export const QUICK_GUIDES = [
  'gs-install-app', 'patient-add', 'patient-search', 'session-log-add', 'bill-create', 'bill-print', 'payment-record',
  'receipt-print', 'ipd-open', 'ipd-add-charges', 'patient-discharge', 'therapist-getting-started', 'users-add',
];

const P = {
  patientsView: 'patients.view',
  patientsCreate: 'patients.create',
  patientsEdit: 'patients.edit',
  discharge: 'patients.dischargeOrClose',
  billsView: 'bills.view',
  billsCreate: 'bills.create',
  billingView: 'billing.view',
  discount: 'billing.discount',
  recordPayment: 'billing.recordPayment',
  backdate: 'billing.backdate',
  sessionsView: 'sessionLogs.view',
  sessionsCreate: 'sessionLogs.create',
  sessionsManage: 'sessionLogs.manage',
  deptView: 'departments.view',
  deptManage: 'departments.manage',
  settlementView: 'hospitalSettlement.view',
  settlementManage: 'hospitalSettlement.manage',
  inquiriesView: 'inquiries.view',
  usersView: 'users.view',
};

const PATIENT_FORM_FIELDS = [
  { label: 'Patient Name', required: true },
  { label: 'Age', required: true },
  { label: 'Gender', required: true },
  { label: 'Address', required: true },
  { label: 'Contact Number 1', required: true },
  { label: 'Contact Number 2' },
  { label: 'Primary Diagnosis', required: true },
  { label: 'Attender Name' },
  { label: 'Attender Contact Number' },
  { label: 'Session Frequency' },
  { label: 'Assigned Therapists' },
];

export const ARTICLES = [
  // ── Getting started ────────────────────────────────────────────────────────
  {
    id: 'gs-sign-in',
    category: 'getting-started',
    title: 'How to sign in (and reset a forgotten password)',
    description: 'Open the staff login, sign in with your email and password, or get a password-reset email.',
    when: 'At the start of every shift, or when you have forgotten your password.',
    keywords: ['login', 'log in', 'password', 'forgot', 'reset', 'sign in'],
    steps: [
      { title: 'Open the staff login page', text: 'Go to the website address followed by /admin (for example www.aarambhhealthsolutions.com/admin). You will see “Staff Sign In”.' },
      { title: 'Enter your email and password', text: 'Type the email address your Super Admin registered for you, and your password.', visual: { fields: [{ label: 'Email', required: true }, { label: 'Password', required: true }] } },
      { title: 'Click Sign In', text: 'You will land on your Dashboard.', visual: { button: 'Sign In', variant: 'primary' } },
      { title: 'Forgot your password?', text: 'Type your email in the Email box first, then click “Forgot password?”. A reset link is emailed to you — open it, choose a new password, and sign in again.', visual: { button: 'Forgot password?', variant: 'link' } },
    ],
    result: 'You are signed in and see the menu for your role.',
    tips: ['New staff receive a “set your password” email when their account is created — use the link in it the first time.', 'Check your spam/junk folder if the email does not arrive within a few minutes.'],
    important: ['If you see “Your account has been deactivated” or “This account no longer has access”, contact your Super Admin.'],
    related: ['gs-navigation', 'trouble-cant-sign-in'],
  },
  {
    id: 'gs-navigation',
    category: 'getting-started',
    title: 'Finding your way around the app',
    description: 'The menu on the left, the notification bell, and signing out — on a computer and on a phone.',
    when: 'Your first day, or whenever you cannot find a page.',
    keywords: ['menu', 'sidebar', 'navigation', 'logout', 'sign out', 'phone', 'mobile', 'hamburger', 'website', 'public site', 'back to dashboard'],
    steps: [
      { title: 'Use the menu on the left', text: 'Every page you can use is listed in the menu. You only see pages your role is allowed to open. On a computer the menu stays in place while you scroll a long page.', visual: { nav: 'Dashboard' } },
      { title: 'On a phone or tablet, tap ☰', text: 'On smaller screens the menu is hidden. Tap the ☰ (menu) button at the top-left to open it; it closes by itself when you choose a page.', visual: { button: 'Open menu', icon: 'Menu', variant: 'ghost' } },
      { title: 'Visit the website and come back', text: 'Click “Website” at the top-right to open the public website in the same tab. A “Back to Dashboard” button appears at the top of the website — click it to return to the page you were on (you stay signed in).', visual: { button: 'Website', icon: 'Globe', variant: 'ghost' } },
      { title: 'Check the bell for things that need attention', text: 'The bell at the top-right shows notifications for your role. A red number means there are unread ones.', visual: { button: 'Notifications', icon: 'Bell', variant: 'ghost' } },
      { title: 'Sign out when you finish', text: 'Click “Logout” at the top-right (on a phone, the arrow icon). Always sign out on a shared computer.', visual: { button: 'Logout', icon: 'LogOut', variant: 'ghost' } },
    ],
    result: 'You can reach every page you need from the menu.',
    tips: ['Lists remember their filters in the address bar — you can bookmark a filtered list in your browser.'],
    related: ['gs-install-app', 'gs-notifications', 'gs-my-access', 'dashboard-overview'],
  },
  {
    id: 'gs-install-app',
    category: 'getting-started',
    title: 'How to install the app on your computer or phone',
    description: 'Put AArambh on your desktop, Start menu, Dock or phone home screen so it opens like an app.',
    when: 'Once on each computer or phone you use for work.',
    keywords: ['install', 'download', 'app', 'desktop', 'home screen', 'pwa', 'windows', 'mac', 'android', 'iphone', 'shortcut'],
    steps: [
      { title: 'Click “Install app” at the top', text: 'It is in the top bar on every page (a ↓ icon on phones), and also on the sign-in page.', visual: { button: 'Install app', icon: 'Download', variant: 'ghost' } },
      { title: 'Windows or Mac (Chrome / Edge): confirm “Install”', text: 'The browser asks “Install app?” — click Install. AArambh gets its own window and an icon on your desktop / Start menu (Windows) or Launchpad and Dock (Mac).' },
      { title: 'Android phone: confirm “Install”', text: 'Tap Install. The AArambh icon appears on your home screen and in your apps.' },
      { title: 'iPhone / iPad, or Safari on a Mac: follow the short steps shown', text: 'These don’t have an install pop-up, so the button shows what to do: on iPhone/iPad use Safari’s Share button → “Add to Home Screen”; in Safari on a Mac use File → “Add to Dock…”.' },
      { title: 'Open it from the icon', text: 'Sign in as usual. The app opens straight on your Dashboard.' },
    ],
    result: 'AArambh opens in its own window like any other app. It is the same system with the same data — nothing separate to update.',
    tips: ['The “Install app” button disappears once you are using the installed app.', 'If the button only shows instructions on a computer, open the page in Chrome or Edge, or use the install icon at the end of the address bar.', 'Updates arrive automatically — there is nothing to download again.'],
    important: ['The app needs an internet connection, the same as the website.', 'On a shared computer, still click Logout when you finish.'],
    related: ['gs-sign-in', 'gs-navigation'],
  },
  {
    id: 'gs-notifications',
    category: 'getting-started',
    title: 'Understanding notifications (the bell)',
    description: 'What the bell shows for your role and how to clear it.',
    when: 'When the bell shows a red number.',
    keywords: ['bell', 'notification', 'alerts', 'unread', 'mark all as read'],
    steps: [
      { title: 'Click the bell', text: 'The panel opens with “Needs attention” (things to act on) and “Recent” (new events).', visual: { button: 'Notifications', icon: 'Bell', variant: 'ghost' } },
      { title: 'Click a notification to go straight there', text: 'Each item opens the right page, already filtered — for example the Outstanding Dues list, or a new patient’s profile.' },
      { title: 'Clear the red number', text: 'Opening an item marks it read. “Mark all as read” clears them all.', visual: { button: 'Mark all as read', variant: 'link' } },
    ],
    result: 'You see only notifications relevant to your role:',
    tips: [
      'Super Admin: new consultation requests, messages, job applications, new patients, account requests, outstanding dues, pending hospital settlement, services that need a price.',
      'Admin: the same, except account requests.',
      'Receptionist: consultation requests, messages and outstanding dues.',
      'Therapist: newly onboarded patients, and a reminder if you have not logged any sessions today.',
    ],
    related: ['gs-navigation', 'dashboard-overview'],
  },
  {
    id: 'gs-my-access',
    category: 'getting-started',
    title: 'What can I do with my account?',
    description: 'A live list of the actions your account is allowed to do.',
    when: 'When you are unsure whether you should be able to do something.',
    keywords: ['permission', 'access', 'role', 'allowed', 'cannot', 'rights'],
    special: 'myAccess',
    steps: [],
    tips: ['Access is set by your role, and a Super Admin can add or remove individual permissions for you.', 'The app checks access on the server too, so a hidden button cannot be worked around.'],
    related: ['trouble-cant-see-menu'],
  },
  {
    id: 'therapist-getting-started',
    category: 'getting-started',
    audience: ['therapist'],
    title: 'Therapist — getting started',
    description: 'Your daily routine in the app: find your patients and record their treatment progress.',
    when: 'Your first day as a therapist, or as a daily checklist.',
    keywords: ['therapist', 'start', 'daily', 'session', 'my patients'],
    steps: [
      { title: 'Sign in', text: 'Use your email and password on the Staff Sign In page.', visual: { button: 'Sign In', variant: 'primary' } },
      { title: 'Look at your Dashboard', text: '“Therapy Sessions” shows how many sessions were logged today (and how many by you). “Patients” shows who is active.', visual: { nav: 'Dashboard' } },
      { title: 'Open Patients', text: 'Find your patient by searching their name, patient code or phone number.', visual: { nav: 'Patients' } },
      { title: 'Open the patient’s profile', text: 'Click the patient’s row. Read the Primary Diagnosis, Session Frequency and the Treatment Progress history before the session.' },
      { title: 'After the session, click “Add Entry”', text: 'In the “Treatment Progress” panel, click “Add Entry”, choose the Session Date and Session Type, write your Progress Notes, and click “Add Session Log”.', visual: { button: 'Add Entry', icon: 'Plus', variant: 'link' } },
      { title: 'Check your day in Therapy Sessions', text: 'Open “Therapy Sessions” and tick “Logged by me” to see everything you recorded today.', visual: { nav: 'Therapy Sessions' } },
    ],
    result: 'Your sessions are recorded on each patient’s profile and counted on the dashboard. If you log nothing by the end of the day, the bell reminds you.',
    tips: ['You can also create a bill for a patient if your clinic asks you to (Bills → Create Bill).', 'Patients assigned to you — and bills for them — are visible to you.'],
    related: ['session-log-add', 'sessions-page', 'therapist-assigned', 'patient-search'],
    action: { label: 'Open Patients', to: '/admin/patients', requires: P.patientsView },
  },

  // ── Dashboard ─────────────────────────────────────────────────────────────
  {
    id: 'dashboard-overview',
    category: 'dashboard',
    title: 'How the Dashboard works',
    description: 'What each section shows, and how to jump to the list behind any number.',
    when: 'Every morning, to see what needs attention.',
    keywords: ['dashboard', 'home', 'overview', 'figures', 'stats', 'reports', 'refresh', 'today'],
    steps: [
      { title: 'Open Dashboard', text: 'It is the first page after you sign in.', visual: { nav: 'Dashboard' } },
      { title: 'Read the sections for your role', text: 'Depending on your access you will see: Patients, Appointments & Visits (patients by type and new consultation requests), Billing, Therapy Sessions, Hospital Settlement, Inquiries, Therapists & Staff, Departments & Services, and Recent Activity.' },
      { title: 'Click any number', text: 'Every card is a link — for example “Active Patients” opens the Patients list already filtered to active patients.' },
      { title: 'Refresh', text: 'Figures update by themselves. “Refresh” confirms you are looking at the latest.', visual: { button: 'Refresh', icon: 'RefreshCw', variant: 'ghost' } },
    ],
    result: 'You know today’s figures and can open the list behind each one.',
    tips: ['There is no separate Reports page — the Dashboard figures, and Billing › Transactions with its filters, are where totals live.'],
    related: ['gs-notifications', 'transactions', 'sessions-page'],
  },

  // ── Patients ──────────────────────────────────────────────────────────────
  {
    id: 'patient-add',
    category: 'patients',
    requires: P.patientsCreate,
    title: 'How to add (register) a new patient',
    description: 'Register a patient, choose how they came to you, and take an advance if they pay one.',
    when: 'When a patient visits for the first time.',
    keywords: ['register', 'new patient', 'onboard', 'add patient', 'admission', 'create patient', 'registration'],
    steps: [
      { title: 'Open Patients', text: 'Click “Patients” in the menu.', visual: { nav: 'Patients' } },
      { title: 'Click “Add Patient”', text: 'It is the blue button at the top-right. The “Onboard New Patient” form opens.', visual: { button: 'Add Patient', icon: 'UserPlus', variant: 'primary' } },
      { title: 'Fill in the patient’s details', text: 'Fields marked * are required. Assigned Therapists is optional — the therapists you tick will be able to see this patient’s bills.', visual: { fields: PATIENT_FORM_FIELDS } },
      { title: 'Choose “Received from / Patient type”', text: 'If a partner hospital referred the patient, pick that hospital under “Referred by hospital (Inpatient)” — the patient becomes an Inpatient of that hospital. Otherwise pick Out Patient, Home Visit or Virtual under “Direct”.', visual: { fields: [{ label: 'Received from / Patient type', required: true }] } },
      { title: 'Enter an advance, if paid', text: 'Type the amount in “Advance Payment (₹)”. Leave it empty if nothing was paid. An advance automatically gets its own receipt.', visual: { fields: [{ label: 'Advance Payment (₹)' }] } },
      { title: 'Click “Create Patient”', text: 'The patient is saved and given a patient code (for example ARCS00010926). Their profile opens.', visual: { button: 'Create Patient', icon: 'UserPlus', variant: 'primary' } },
    ],
    result: 'The patient appears in the Patients list with their code, and can now be billed, have sessions logged, and receive payments.',
    tips: ['Check the phone number carefully — you can search by it later.', 'Choosing the hospital here means their bills are automatically branded with that hospital; direct patients are billed under your own hospital.', 'From Billing › Bill a Patient you can also onboard a patient who is not found — you go straight to Create Bill afterwards.'],
    important: ['Patient type cannot be changed later by editing. It only changes when a patient is discharged and readmitted.'],
    related: ['patient-search', 'patient-edit', 'bill-create', 'payment-advance'],
    action: { label: 'Open Patients', to: '/admin/patients', requires: P.patientsView },
  },
  {
    id: 'patient-search',
    category: 'patients',
    requires: P.patientsView,
    title: 'How to find an existing patient',
    description: 'Search by patient code, name or phone number, or filter the list.',
    when: 'Whenever a returning patient comes in.',
    keywords: ['find', 'search', 'lookup', 'old patient', 'existing', 'phone', 'code', 'filter'],
    steps: [
      { title: 'Open Patients', text: '', visual: { nav: 'Patients' } },
      { title: 'Type in the search box', text: 'Enter the patient code (e.g. ARCS00010926), the start of their name, or their phone number. Results appear as you type.', visual: { fields: [{ label: 'Search by patient code, name, or phone number…' }] } },
      { title: 'Or use the filters', text: 'Filter by type and status, “Hospital-referred”, or “New this month”. The list shows the latest 100 matches.', visual: { chips: ['All Types', 'Inpatient', 'Outpatient', 'Home Visit', 'Virtual', 'Active', 'Discharged', 'All', 'Hospital-referred', 'New this month'], active: ['All Types', 'Active'] } },
      { title: 'Click the patient', text: 'Their profile opens.' },
    ],
    result: 'You are on the patient’s profile.',
    tips: ['Name search matches the beginning of the name — “Ash” finds “Asha Rao”.', 'Discharged patients are hidden by the default “Active” filter — choose “All” or “Discharged”.'],
    related: ['patient-profile', 'trouble-cant-find-patient'],
    action: { label: 'Open Patients', to: '/admin/patients', requires: P.patientsView },
  },
  {
    id: 'patient-profile',
    category: 'patients',
    requires: P.patientsView,
    title: 'Reading a patient’s profile and history',
    description: 'Everything about one patient: details, visits, treatment progress, bills and payments.',
    when: 'Before a session, before billing, or when a patient asks about their account.',
    keywords: ['profile', 'history', 'details', 'encounter', 'visits', 'record'],
    steps: [
      { title: 'Open the patient', text: 'Find them in Patients and click their row.', visual: { nav: 'Patients' } },
      { title: 'Details', text: 'Primary Diagnosis, Contact, Address, Attender, Advance Paid, Assigned Therapists and more are shown at the top.' },
      { title: 'Encounter History', text: 'Every visit/admission with its start and end date. Inpatient admissions have an “IPD bill” link.' },
      { title: 'Treatment Progress', text: 'Every session logged by therapists, newest first.' },
      { title: 'Bills and Patient Balance', text: 'Staff with billing access also see the patient’s bills, their balance, and the full Transaction History with a “Receipt” link on each payment.' },
    ],
    result: 'You have the patient’s complete picture on one page.',
    related: ['patient-edit', 'session-log-add', 'payment-record', 'ipd-open'],
  },
  {
    id: 'patient-edit',
    category: 'patients',
    requires: P.patientsEdit,
    title: 'How to update a patient’s information',
    description: 'Correct details such as phone, address, diagnosis, referring hospital or assigned therapists.',
    when: 'When a patient’s details change or were entered wrongly.',
    keywords: ['edit', 'update', 'change', 'correct', 'phone number', 'address', 'referring hospital'],
    steps: [
      { title: 'Open the patient’s profile', text: '', visual: { nav: 'Patients' } },
      { title: 'Click “Edit”', text: 'The “Edit Patient Details” form opens.', visual: { button: 'Edit', icon: 'Pencil', variant: 'ghost' } },
      { title: 'Change what you need', text: 'All the registration fields can be edited, plus “Referred by hospital” and Assigned Therapists.', visual: { fields: [...PATIENT_FORM_FIELDS.slice(0, 7), { label: 'Referred by hospital' }, { label: 'Assigned Therapists' }] } },
      { title: 'Click “Save Changes”', text: '', visual: { button: 'Save Changes', icon: 'Save', variant: 'primary' } },
    ],
    result: 'The profile shows the new details. Changing Assigned Therapists also updates which therapists can see the patient’s bills.',
    important: ['Existing bills keep the details printed on them when they were made — that is deliberate, bills are financial records.'],
    related: ['therapist-assigned', 'patient-profile'],
  },
  {
    id: 'patient-discharge',
    category: 'patients',
    requires: P.discharge,
    title: 'How to discharge a patient (or mark them inactive)',
    description: 'Close the patient’s current visit once their account is settled.',
    when: 'When an inpatient leaves, or an out-patient’s treatment ends.',
    keywords: ['discharge', 'mark inactive', 'close', 'check out', 'checkout', 'leave'],
    steps: [
      { title: 'Settle the account first', text: 'The patient’s balance must be zero or in credit. Check “Patient Balance” on the profile; record the remaining payment if needed.', visual: { button: 'Record Payment', icon: 'CreditCard', variant: 'ghost' } },
      { title: 'For inpatients, print the final bill', text: 'Open their IPD bill, tick “Final discharge bill (whole stay)”, and click “Print Bill”.', visual: { button: 'Print Bill', icon: 'Printer', variant: 'primary' } },
      { title: 'Click “Discharge” (or “Mark Inactive”)', text: 'Inpatients show “Discharge”; other patients show “Mark Inactive”.', visual: { button: 'Discharge', variant: 'ghost' } },
    ],
    result: 'The visit is closed and the patient shows as Discharged. They can be readmitted later.',
    important: ['The button is disabled while the patient has pending dues (“Clear pending dues before discharging”).'],
    related: ['ipd-final-bill', 'patient-readmit', 'payment-record', 'trouble-cant-discharge'],
  },
  {
    id: 'patient-readmit',
    category: 'patients',
    requires: P.discharge,
    title: 'How to readmit a returning patient',
    description: 'Start a new visit or admission for a patient who was discharged.',
    when: 'When a discharged patient comes back.',
    keywords: ['readmit', 'return', 'new visit', 'admit again', 'admission'],
    steps: [
      { title: 'Find the patient', text: 'In Patients, choose the “Discharged” or “All” filter, or search.', visual: { nav: 'Patients' } },
      { title: 'Click “Readmit”', text: 'On their profile.', visual: { button: 'Readmit', variant: 'ghost' } },
      { title: 'Choose the patient type and confirm', text: 'Choose Inpatient, Outpatient, Home Visit or Virtual, then click “Readmit Patient”.', visual: { button: 'Readmit Patient', variant: 'primary' } },
    ],
    result: 'A new visit starts. If you chose Inpatient, a new IPD running bill (with its own number) can be opened for this stay.',
    related: ['ipd-admit', 'patient-discharge'],
  },
  {
    id: 'patient-trash',
    category: 'patients',
    requires: 'superadmin',
    title: 'Deleting a patient (Move to Trash)',
    description: 'Remove a patient registered by mistake — they can be restored.',
    when: 'Only for duplicate or mistaken registrations.',
    keywords: ['delete patient', 'remove', 'duplicate', 'trash'],
    steps: [
      { title: 'Open the patient’s profile and click “Move to Trash”', text: '', visual: { button: 'Move to Trash', icon: 'Trash2', variant: 'danger' } },
      { title: 'Type the patient’s name exactly and confirm', text: 'The patient, their visits, bills and sessions disappear from every list and total.' },
    ],
    result: 'The patient is in Trash › Patients and can be restored with everything intact.',
    related: ['trash-restore'],
  },

  // ── Therapy ───────────────────────────────────────────────────────────────
  {
    id: 'session-log-add',
    category: 'therapy',
    requires: P.sessionsCreate,
    title: 'How to record a therapy session (treatment progress)',
    description: 'Add today’s treatment notes to a patient’s record.',
    when: 'After each therapy session.',
    keywords: ['session', 'treatment', 'notes', 'progress', 'consultation', 'therapy', 'log', 'start session', 'record treatment'],
    steps: [
      { title: 'Open the patient’s profile', text: '', visual: { nav: 'Patients' } },
      { title: 'In “Treatment Progress”, click “Add Entry”', text: '', visual: { button: 'Add Entry', icon: 'Plus', variant: 'link' } },
      { title: 'Fill in the session', text: 'Session Date (today by default), Session Type (Free Session, Physiotherapy — Morning, Physiotherapy — Afternoon, OT Session) and your Progress Notes.', visual: { fields: [{ label: 'Session Date', required: true }, { label: 'Session Type', required: true }, { label: 'Progress Notes' }] } },
      { title: 'Click “Add Session Log”', text: '', visual: { button: 'Add Session Log', variant: 'primary' } },
    ],
    result: 'The entry appears at the top of Treatment Progress and is counted on the Dashboard and in Therapy Sessions.',
    tips: ['Write notes another therapist could follow tomorrow — what was done, how the patient responded, what to do next.'],
    important: ['Only an Admin or Super Admin can edit or delete a session entry, so check before saving.'],
    related: ['sessions-page', 'session-log-edit', 'therapist-getting-started'],
  },
  {
    id: 'session-log-edit',
    category: 'therapy',
    requires: P.sessionsManage,
    title: 'Editing or deleting a session entry',
    description: 'Correct a mistake in a treatment progress entry.',
    when: 'When a session was logged with the wrong date, type or notes.',
    keywords: ['edit session', 'delete session', 'correct notes'],
    steps: [
      { title: 'Open the patient’s profile', text: 'Find the entry in “Treatment Progress”.' },
      { title: 'Click the pencil to edit, or the bin to delete', text: 'Editing opens “Edit Session Log” — change it and click “Save Changes”.', visual: { button: 'Save Changes', variant: 'primary' } },
    ],
    result: 'The entry is corrected everywhere it is counted.',
    related: ['session-log-add'],
  },
  {
    id: 'sessions-page',
    category: 'therapy',
    requires: P.sessionsView,
    title: 'Seeing all sessions (today, this week, by me)',
    description: 'Every patient’s session logs in one list.',
    when: 'To check the day’s work, or a therapist’s own sessions.',
    keywords: ['therapy sessions', 'today', 'sessions list', 'logged by me', 'my sessions', 'previous sessions'],
    steps: [
      { title: 'Open Therapy Sessions', text: '', visual: { nav: 'Therapy Sessions' } },
      { title: 'Choose the period and type', text: 'Today, Last 7 days, This month or All time; filter by session type; tick “Logged by me” for your own.', visual: { chips: ['Today', 'Last 7 days', 'This month', 'All time', 'Logged by me'], active: ['Today'] } },
      { title: 'Click a session to open that patient', text: '' },
    ],
    result: 'You see exactly which sessions were logged, by whom.',
    tips: ['New sessions are added from the patient’s profile, not from this page.'],
    related: ['session-log-add'],
    action: { label: 'Open Therapy Sessions', to: '/admin/sessions', requires: P.sessionsView },
  },
  {
    id: 'therapist-assigned',
    category: 'therapy',
    audience: ['therapist'],
    title: 'Your assigned patients and the bills you can see',
    description: 'Why you see some bills and not others.',
    when: 'When you are looking for a patient’s bill.',
    keywords: ['assigned', 'my patients', 'which bills', 'visible', 'cannot see bill'],
    steps: [
      { title: 'Open Bills', text: 'You see bills you created, bills where you are the prescribing physician, bills for patients assigned to you, and bills containing services from your departments.', visual: { nav: 'Bills' } },
      { title: 'Ask for an assignment if a patient is missing', text: 'A receptionist or admin adds you under “Assigned Therapists” on the patient (Edit). You then see that patient’s bills — including older ones.' },
    ],
    result: 'You see the bills relevant to your patients.',
    tips: ['Your departments are set by the Super Admin in Settings › Therapists.'],
    related: ['bills-list', 'patient-edit'],
  },

  // ── Bills ─────────────────────────────────────────────────────────────────
  {
    id: 'bill-create',
    category: 'bills',
    requires: P.billsCreate,
    title: 'How to create a bill (medical invoice)',
    description: 'Make an invoice for a patient’s services — it is added to their balance automatically.',
    when: 'When a patient has received services that need to be charged.',
    keywords: ['bill', 'invoice', 'create bill', 'charge', 'new bill', 'billing'],
    steps: [
      { title: 'Start a new bill', text: 'Click “Bills” then “Create Bill” — or click “Create Bill” on the patient’s profile (the patient is filled in for you).', visual: { nav: 'Bills' } },
      { title: 'Click “Create Bill”', text: '', visual: { button: 'Create Bill', icon: 'FilePlus', variant: 'primary' } },
      { title: '① Patient', text: 'The form is in numbered sections (side by side on a computer). Type any part of the patient’s name, code or phone — results appear as you type (↑ ↓ and Enter work too). Once chosen, only the name shows; click “Change” to adjust the name, phone and address printed on the bill, or to choose a different patient.', visual: { fields: [{ label: 'Name on bill' }, { label: 'Phone' }, { label: 'Address' }, { label: 'City / State / PIN' }] } },
      { title: '② Hospital & Physician', text: 'The hospital is picked for you from the patient (their referring hospital, or your own hospital for direct patients), and the physician from their assigned therapist. The box then shows just the two names — click the arrow to open it and change them.', visual: { fields: [{ label: 'Hospital', required: true }, { label: 'Prescribing physician (therapist)' }] } },
      { title: '③ Services', text: 'Start typing a service — suggestions appear below; picking one fills in its department too. Click “Add” (or press Enter) — the price fills in. Choose a department first to see only its services. Use “Custom item” for anything not in the catalog.', visual: { button: 'Add', icon: 'Plus', variant: 'primary' } },
      { title: '④ Dates and ⑤ Discount, Tax & Notes', text: 'Set the due date. Enter a discount if allowed (% or ₹). Tax is applied automatically. Add notes if needed. The Bill Summary box shows the total, and the live preview below the form shows the bill as you type.', visual: { fields: [{ label: 'Discount' }, { label: 'Tax' }, { label: 'Notes' }] } },
      { title: 'Click “Save Bill”', text: 'It is in the Bill Summary box.', visual: { button: 'Save Bill', icon: 'Save', variant: 'primary' } },
    ],
    result: 'The bill gets a number (patient code + 0001, 0002…), shows who billed it, and its total is added to the patient’s balance. You land on the bill, ready to print.',
    tips: ['Printing is optional — the charge is recorded either way.', 'Billing › Bill a Patient is another way in: search the patient and you go straight to Create Bill.'],
    important: ['After saving, only an Admin or Super Admin can edit or delete the bill.'],
    related: ['bill-add-items', 'bill-print', 'bill-discount', 'bill-tax', 'payment-record'],
    action: { label: 'Create a bill', to: '/admin/bills/new', requires: P.billsCreate },
  },
  {
    id: 'bill-add-items',
    category: 'bills',
    requires: P.billsCreate,
    title: 'Adding services to a bill (section ③ Services)',
    description: 'Catalog services with their prices, custom items, editing and removing lines.',
    when: 'While creating or editing a bill.',
    keywords: ['items', 'services', 'add service', 'custom item', 'price', 'line'],
    steps: [
      { title: 'Type a service and pick a suggestion', text: 'Suggestions appear as you type, from every department (its department fills in for you). Optionally choose a department first to narrow the list. Only services that have a price appear. Click “Add” or press Enter.', visual: { button: 'Add', icon: 'Plus', variant: 'primary' } },
      { title: 'Or click “Custom item”', text: 'A blank line appears — type the item, description and price.', visual: { button: 'Custom item', icon: 'Plus', variant: 'link' } },
      { title: 'Edit or remove lines', text: 'Each line has Item, Description and Price side by side — change them directly; the bin at the end of the line removes it.' },
    ],
    result: 'The subtotal and total update as you go.',
    tips: ['“No priced services in this department” means it has no prices yet — ask the Super Admin to set prices in Departments.'],
    related: ['bill-create', 'services-manage'],
  },
  {
    id: 'bill-discount',
    category: 'bills',
    requires: [P.billsCreate, P.discount],
    title: 'How to apply a discount',
    description: 'Give a percentage or fixed-amount discount on a bill.',
    when: 'When a discount has been approved for the patient.',
    keywords: ['discount', 'concession', 'reduce', 'percent', 'off'],
    steps: [
      { title: 'In “Discount, Tax & Notes”, choose % or ₹', text: '', visual: { chips: ['%', '₹'], active: ['%'] } },
      { title: 'Type the discount', text: 'A % discount is taken from the subtotal; a ₹ discount is a fixed amount (never more than the subtotal).', visual: { fields: [{ label: 'Discount' }] } },
    ],
    result: 'The preview and total update immediately; the invoice shows the discount line.',
    related: ['bill-tax', 'bill-create'],
  },
  {
    id: 'bill-tax',
    category: 'bills',
    requires: P.billsView,
    title: 'How tax is calculated',
    description: 'Where the tax percentage comes from and how it is applied.',
    when: 'When a patient asks about the tax on their bill.',
    keywords: ['tax', 'gst', 'percentage', 'calculation', 'total'],
    steps: [
      { title: 'The Super Admin sets one tax %', text: 'In Settings › Bill Settings › “Tax on bills”. Every new bill uses it automatically — nobody types it on the bill.' },
      { title: 'Tax is charged after discount', text: 'Total = Subtotal − Discount + Tax, where Tax = tax % of (Subtotal − Discount).' },
      { title: 'Old bills keep their tax', text: 'If the tax % changes later, bills already issued keep the tax they were created with — even when edited.' },
    ],
    result: 'Example: Subtotal ₹800, 10% discount (₹80), 5% tax on ₹720 (₹36) → Total ₹756.',
    related: ['settings-bill', 'bill-discount'],
  },
  {
    id: 'bill-print',
    category: 'bills',
    requires: P.billsView,
    title: 'How to print a bill or save it as PDF',
    description: 'Print only the A4 invoice — no menus or buttons.',
    when: 'When the patient wants a copy of the bill.',
    keywords: ['print', 'pdf', 'download', 'invoice copy', 'save pdf', 'detailed bill', 'cash due', 'paid amount', 'refundable'],
    steps: [
      { title: 'Open the bill', text: 'From Bills, or the patient’s profile, or right after saving.', visual: { nav: 'Bills' } },
      { title: 'Click “Print Invoice”', text: 'Your browser’s print window opens with just the bill on A4 (a long bill continues on a second page).', visual: { button: 'Print Invoice', icon: 'Printer', variant: 'primary' } },
      { title: 'For a PDF, click “Download PDF”', text: 'In the print window choose “Save as PDF” as the destination (Printer), then Save. The file is named after the bill number.', visual: { button: 'Download PDF', icon: 'Download', variant: 'ghost' } },
    ],
    result: 'A hospital detailed bill (OPD / IPD / Home Visit / Virtual Consultation, by the patient’s visit) branded with the bill’s hospital: patient and admission details, services grouped by department with Rate, Unit, Dis%, GST% and amounts, Service Total, Discount, GST and Final Amount, the visit’s payments with receipt numbers, Paid Amount, Cash Due, Credit Due and Refundable Amount, amount in words, and who printed it.',
    tips: ['Payments are not tied to one bill, so the Payments part lists every payment for the patient’s current visit or admission, and Cash Due / Credit Due are for that whole visit.', 'Discount and GST apply to the whole bill, so the service lines show 0 and the totals show the real Discount and GST.', 'Panel shows Cash and Claim No shows N/A — the app does not handle insurance panels.'],
    related: ['printing-tips', 'receipt-print', 'trouble-print'],
  },
  {
    id: 'bills-list',
    category: 'bills',
    requires: P.billsView,
    title: 'Finding a bill',
    description: 'Search and filter the list of bills.',
    when: 'When you need an older bill.',
    keywords: ['find bill', 'bill list', 'search bill', 'old bill'],
    steps: [
      { title: 'Open Bills', text: '', visual: { nav: 'Bills' } },
      { title: 'Search or filter', text: 'Search by bill number or patient; filter by date, hospital (when you have more than one), or “Created by me”.', visual: { chips: ['All time', 'Today', 'This month', 'Created by me'], active: ['All time'] } },
      { title: 'Click a bill to open it', text: '' },
    ],
    result: 'The bill opens, ready to view or print.',
    tips: ['A patient’s own bills are also listed on their profile.'],
    related: ['bill-print', 'therapist-assigned'],
    action: { label: 'Open Bills', to: '/admin/bills', requires: P.billsView },
  },
  {
    id: 'bill-correct',
    category: 'bills',
    requires: 'adminOrAbove',
    title: 'How to correct or delete a bill (Admin)',
    description: 'Edit a saved bill, or move it to the Trash — the patient’s balance follows.',
    when: 'When a bill was saved with a mistake.',
    keywords: ['edit bill', 'correct bill', 'delete bill', 'wrong bill', 'cancel bill', 'mistake'],
    steps: [
      { title: 'Open the bill and click “Edit”', text: '', visual: { button: 'Edit', icon: 'Pencil', variant: 'ghost' } },
      { title: 'Fix it and click “Save Changes”', text: 'The bill number stays the same. The change is recorded in the audit log.', visual: { button: 'Save Changes', icon: 'Save', variant: 'primary' } },
      { title: 'Or remove it with “Move to Trash”', text: 'Type the bill number to confirm. Its charge leaves the patient’s balance.', visual: { button: 'Move to Trash', icon: 'Trash2', variant: 'danger' } },
    ],
    result: 'The balance, dues and dashboard update. A Super Admin can restore a trashed bill from Trash › Bills.',
    related: ['trash-restore', 'bill-create'],
  },

  // ── Payments ──────────────────────────────────────────────────────────────
  {
    id: 'payment-record',
    category: 'payments',
    requires: P.recordPayment,
    title: 'How to record a patient payment',
    description: 'Take a payment, reduce the balance, and print a receipt.',
    when: 'Whenever a patient pays.',
    keywords: ['payment', 'pay', 'collect', 'receive money', 'cash', 'upi', 'card', 'record payment'],
    steps: [
      { title: 'Open the patient’s profile', text: 'Scroll to “Patient Balance”.', visual: { nav: 'Patients' } },
      { title: 'Click “Record Payment”', text: '', visual: { button: 'Record Payment', icon: 'CreditCard', variant: 'ghost' } },
      { title: 'Fill in the payment', text: 'Amount, Payment Method (Cash, Card, UPI, Bank Transfer, Cheque, Other), and optionally a Reference (cheque no., transaction ID) and Remarks.', visual: { fields: [{ label: 'Amount (₹)', required: true }, { label: 'Payment Method', required: true }, { label: 'Reference' }, { label: 'Remarks' }] } },
      { title: 'Click “Record Payment”', text: '', visual: { button: 'Record Payment', icon: 'Check', variant: 'primary' } },
      { title: 'Print the receipt', text: '“Payment Recorded” shows the receipt number. Click “View & Print Receipt”, or “Done”.', visual: { button: 'View & Print Receipt', icon: 'FileText', variant: 'primary' } },
    ],
    result: 'The payment is saved as its own entry with a receipt number (patient code + R0001, R0002…), and the balance goes down.',
    tips: ['Every payment is kept separately — nothing is overwritten.', 'Staff allowed to backdate also see a Payment Date field.'],
    related: ['receipt-print', 'outstanding-dues', 'payment-wrong-amount', 'ipd-interim-payment'],
  },
  {
    id: 'receipt-print',
    category: 'payments',
    requires: P.billingView,
    title: 'How to print a payment receipt',
    description: 'Every payment has an A4 receipt with the amount in words.',
    when: 'When a patient wants proof of payment.',
    keywords: ['receipt', 'print receipt', 'payment proof', 'pdf'],
    steps: [
      { title: 'Find the payment', text: 'On the patient’s profile, in Transaction History, click “Receipt” next to the payment. (Right after recording, use “View & Print Receipt”.)', visual: { button: 'Receipt', variant: 'link' } },
      { title: 'Click “Print Receipt” or “Download PDF”', text: 'For a PDF, choose “Save as PDF” in the print window.', visual: { button: 'Print Receipt', icon: 'Printer', variant: 'primary' } },
    ],
    result: 'A receipt branded with the patient’s hospital, showing receipt number, date, method, reference, who received it, and the amount in figures and words.',
    tips: ['Payments recorded before receipts were introduced have a number starting with PAY-.'],
    related: ['payment-record', 'printing-tips'],
  },
  {
    id: 'payment-advance',
    category: 'payments',
    requires: P.patientsCreate,
    title: 'How to handle an advance payment',
    description: 'Take an advance at registration or later.',
    when: 'When a patient pays before services are charged.',
    keywords: ['advance', 'deposit', 'prepay', 'credit'],
    steps: [
      { title: 'At registration', text: 'Enter it in “Advance Payment (₹)” on the Onboard New Patient form — it becomes receipt R0001.', visual: { fields: [{ label: 'Advance Payment (₹)' }] } },
      { title: 'Later', text: 'Use “Record Payment” on the profile (or “Add Payment” on an IPD bill). Bills are then taken out of the advance automatically.', visual: { button: 'Record Payment', icon: 'CreditCard', variant: 'ghost' } },
    ],
    result: 'The patient’s balance shows a credit, and later bills reduce it.',
    related: ['payment-record', 'ipd-balance'],
  },
  {
    id: 'outstanding-dues',
    category: 'payments',
    requires: P.billingView,
    title: 'How to see outstanding balances (dues)',
    description: 'Who owes money, and how much.',
    when: 'For follow-up calls, or before discharge.',
    keywords: ['outstanding', 'dues', 'balance', 'owed', 'pending', 'due'],
    steps: [
      { title: 'Open Billing', text: '', visual: { nav: 'Billing' } },
      { title: 'Click “Outstanding Dues”', text: 'Patients with money due, largest first, with contact number and last activity.', visual: { tabs: ['Bill a Patient', 'Outstanding Dues', 'Transactions'], active: 'Outstanding Dues' } },
      { title: 'Or check one patient', text: 'Their profile shows “Pending Dues” at the top and the exact “Patient Balance”.' },
    ],
    result: 'You know who to follow up with.',
    related: ['payment-record', 'transactions'],
    action: { label: 'Open Outstanding Dues', to: '/admin/billing?view=outstanding', requires: P.billingView },
  },
  {
    id: 'transactions',
    category: 'payments',
    requires: P.billingView,
    title: 'Viewing all transactions (collections and charges)',
    description: 'Every charge and payment across patients, with totals.',
    when: 'For end-of-day totals or finding a specific payment.',
    keywords: ['transactions', 'collections', 'today total', 'cash collected', 'report', 'daily'],
    steps: [
      { title: 'Open Billing › Transactions', text: '', visual: { tabs: ['Bill a Patient', 'Outstanding Dues', 'Transactions'], active: 'Transactions' } },
      { title: 'Filter', text: 'Choose the period (Today, This month, All time), Charges or Payments, payment method, or service. Totals for Charged, Collected and Discounts update.', visual: { chips: ['Today', 'This month', 'All time', 'Charges', 'Payments'], active: ['Today'] } },
    ],
    result: 'You have the day’s (or month’s) figures.',
    related: ['outstanding-dues', 'dashboard-overview'],
    action: { label: 'Open Transactions', to: '/admin/billing?view=transactions', requires: P.billingView },
  },
  {
    id: 'payment-wrong-amount',
    category: 'payments',
    requires: P.billingView,
    title: 'I entered the wrong payment amount',
    description: 'How a wrong payment is corrected — and who can do it.',
    when: 'Immediately after noticing the mistake.',
    keywords: ['wrong amount', 'mistake', 'correct payment', 'refund', 'error', 'wrong payment'],
    steps: [
      { title: 'Do not record a second “balancing” payment', text: 'Tell an Admin or Super Admin the patient, receipt number and the correct amount.' },
      { title: 'Admin: on an IPD bill, use “Correct payment”', text: 'In the IPD bill’s Payments Received tab, click the pencil next to the payment, change the amount/mode/remarks and save. The receipt number stays the same.', visual: { button: 'Save Correction', variant: 'primary' } },
      { title: 'Admin: elsewhere, move it to the Trash and record it again', text: 'On the profile’s Transaction History, the bin moves the wrong payment to the Trash; then record the correct payment.', visual: { button: 'Move to Trash', icon: 'Trash2', variant: 'danger' } },
    ],
    result: 'The balance is right, and the audit log keeps what was changed and by whom.',
    important: ['Receptionists cannot change or remove payments — contact your administrator.'],
    related: ['ipd-corrections', 'payment-record'],
  },

  // ── IPD ───────────────────────────────────────────────────────────────────
  {
    id: 'ipd-admit',
    category: 'ipd',
    requires: P.patientsCreate,
    title: 'How to admit a patient (Inpatient)',
    description: 'A patient becomes an inpatient at registration, or by readmission.',
    when: 'When a patient is admitted for a stay.',
    keywords: ['admit', 'admission', 'inpatient', 'ipd', 'hospital admission'],
    steps: [
      { title: 'New patient: register them', text: 'In “Received from / Patient type”, choose the hospital under “Referred by hospital (Inpatient)”.', visual: { fields: [{ label: 'Received from / Patient type', required: true }] } },
      { title: 'Returning patient: readmit', text: 'On their profile, click “Readmit” and choose Inpatient (needs discharge permission).', visual: { button: 'Readmit', variant: 'ghost' } },
      { title: 'Open their IPD bill and add ward/room', text: 'Billing › IPD / Hospital Running Bill, choose the patient and admission, then “Ward, room & doctor”.' },
    ],
    result: 'The admission appears in Encounter History, and an IPD running bill can be kept for the stay.',
    related: ['patient-add', 'ipd-open', 'ipd-admission-details'],
  },
  {
    id: 'ipd-open',
    category: 'ipd',
    requires: P.billingView,
    title: 'How to open an IPD running bill',
    description: 'Find an admitted patient’s running bill (account statement for the stay).',
    when: 'Whenever you add charges or payments for an inpatient, or print their bill.',
    keywords: ['ipd', 'running bill', 'inpatient bill', 'hospital bill', 'statement', 'admission bill'],
    steps: [
      { title: 'Open Billing', text: '', visual: { nav: 'Billing' } },
      { title: 'Click “IPD / Hospital Running Bill”', text: '', visual: { button: 'IPD / Hospital Running Bill', icon: 'BedDouble', variant: 'ghost' } },
      { title: 'Choose the patient', text: '“Currently admitted” patients are listed; or search any patient.' },
      { title: 'Choose the admission', text: 'Each stay has its own bill. The first time it opens it gets an IPD bill number, e.g. ARCS00010926-IP1.' },
    ],
    result: 'The running bill shows the patient, admission details, totals, and tabs: Charges by Day, Payments Received, Account Ledger and Bill Preview.',
    tips: ['Shortcut: on the patient’s profile, Encounter History has an “IPD bill” link next to each inpatient admission.'],
    related: ['ipd-add-charges', 'ipd-interim-payment', 'ipd-balance', 'ipd-final-bill'],
    action: { label: 'Open IPD Running Bills', to: '/admin/billing/ipd', requires: P.billingView },
  },
  {
    id: 'ipd-admission-details',
    category: 'ipd',
    requires: [P.billingView, P.patientsEdit],
    title: 'Recording ward, room/bed and treating doctor',
    description: 'Admission details printed on the IPD bill.',
    when: 'At admission, or when the patient changes room.',
    keywords: ['ward', 'room', 'bed', 'doctor', 'expected discharge'],
    steps: [
      { title: 'Open the IPD bill and click “Ward, room & doctor”', text: '', visual: { button: 'Ward, room & doctor', icon: 'Pencil', variant: 'link' } },
      { title: 'Fill in the details and save', text: '', visual: { fields: [{ label: 'Ward' }, { label: 'Room / Bed' }, { label: 'Treating doctor' }, { label: 'Expected discharge date' }] } },
    ],
    result: 'They show on the account and on every printed IPD bill.',
    related: ['ipd-open'],
  },
  {
    id: 'ipd-add-charges',
    category: 'ipd',
    requires: [P.billingView, P.billsCreate],
    title: 'Adding charges during a stay (room rent, medicines, tests…)',
    description: 'Add one charge, or the same charge for every day (e.g. room rent).',
    when: 'Whenever a service is given to an admitted patient.',
    keywords: ['room rent', 'charges', 'medicines', 'pharmacy', 'nursing', 'investigation', 'add service', 'daily', 'ipd charge'],
    steps: [
      { title: 'On the IPD bill, click “Add Charge”', text: 'In the Charges by Day tab.', visual: { button: 'Add Charge', icon: 'Plus', variant: 'primary' } },
      { title: 'Fill in the charge', text: 'Date (within the stay), Category (Room Rent, Consultation, Pharmacy, Investigation…), optionally a service from the catalog, Service name, Description, Qty and Rate. Amount = Qty × Rate.', visual: { fields: [{ label: 'Date', required: true }, { label: 'Category', required: true }, { label: 'From service catalog' }, { label: 'Service' }, { label: 'Description' }, { label: 'Qty', required: true }, { label: 'Rate (₹)', required: true }] } },
      { title: 'Room rent for many days? Use “Repeat daily until”', text: 'Choose the last day — one charge per day is added in one go (the button shows how many and the total).', visual: { fields: [{ label: 'Repeat daily until' }] } },
      { title: 'Click “Add Charge”', text: '', visual: { button: 'Add Charge', variant: 'primary' } },
    ],
    result: 'Each charge gets a number (e.g. …-IP1/C007), appears under its day with a daily total, and the outstanding balance updates.',
    tips: ['Catalog prices can only be changed by an Admin.', 'Normal bills made for the patient during the stay also appear here on their date.'],
    related: ['ipd-balance', 'ipd-corrections', 'ipd-open'],
  },
  {
    id: 'ipd-interim-payment',
    category: 'ipd',
    requires: [P.billingView, P.recordPayment],
    title: 'Taking payments during a stay (advance and interim)',
    description: 'Every payment during the stay is kept separately with its own receipt.',
    when: 'At admission and whenever the patient pays during the stay.',
    keywords: ['interim payment', 'advance', 'deposit', 'ipd payment', 'part payment'],
    steps: [
      { title: 'On the IPD bill, open “Payments Received”', text: '', visual: { tabs: ['Charges by Day', 'Payments Received', 'Account Ledger', 'Bill Preview'], active: 'Payments Received' } },
      { title: 'Click “Add Payment”', text: 'Remarks are pre-filled (“Advance at admission” or “Interim payment”) — change them if needed.', visual: { button: 'Add Payment', icon: 'CreditCard', variant: 'primary' } },
      { title: 'Record it and print the receipt', text: '', visual: { button: 'View & Print Receipt', icon: 'FileText', variant: 'primary' } },
    ],
    result: 'The payment is listed with date, receipt number, mode and remarks; “Payments received” and the balance update.',
    related: ['ipd-balance', 'receipt-print', 'payment-record'],
  },
  {
    id: 'ipd-balance',
    category: 'ipd',
    requires: P.billingView,
    title: 'Reading the running balance',
    description: 'Total charges, payments received, and outstanding or credit — for the whole stay or a period.',
    when: 'Whenever the patient or family asks how much is due.',
    keywords: ['balance', 'outstanding', 'credit', 'ledger', 'brought forward', 'period', 'statement'],
    steps: [
      { title: 'Look at the totals', text: '“Total charges”, “Payments received”, and one of: Outstanding Amount (patient owes), Fully Paid, or Advance / Credit Balance (patient has paid more).' },
      { title: 'Choose a period (optional)', text: 'Use From/To for part of the stay. Anything before “From” appears as “Brought forward”, so the balance is always correct.', visual: { fields: [{ label: 'From' }, { label: 'To' }] } },
      { title: 'See the full ledger', text: 'The “Account Ledger” tab lists every charge (debit) and payment (credit) with the running balance.', visual: { tabs: ['Charges by Day', 'Payments Received', 'Account Ledger', 'Bill Preview'], active: 'Account Ledger' } },
    ],
    result: 'You can explain exactly how the balance was reached.',
    tips: ['Length of stay counts the admission day and the discharge (or current) day.'],
    related: ['ipd-final-bill', 'ipd-print'],
  },
  {
    id: 'ipd-print',
    category: 'ipd',
    requires: P.billingView,
    title: 'Printing the IPD running bill',
    description: 'An interim statement for any period, on A4.',
    when: 'When the family asks for the bill so far.',
    keywords: ['print ipd', 'interim bill', 'running bill print', 'statement pdf'],
    steps: [
      { title: 'Check it in “Bill Preview”', text: '', visual: { tabs: ['Charges by Day', 'Payments Received', 'Account Ledger', 'Bill Preview'], active: 'Bill Preview' } },
      { title: 'Click “Print Bill” (or “Download PDF”)', text: 'Longer stays print over several pages with the table headings repeated.', visual: { button: 'Print Bill', icon: 'Printer', variant: 'primary' } },
    ],
    result: 'An “IPD Running Bill — Interim Statement” with charges by date, payment receipts, totals and the balance.',
    related: ['ipd-final-bill', 'printing-tips'],
  },
  {
    id: 'ipd-final-bill',
    category: 'ipd',
    requires: P.billingView,
    title: 'Generating the final discharge bill',
    description: 'The complete account for the whole stay, printed at discharge.',
    when: 'On the day of discharge.',
    keywords: ['final bill', 'discharge bill', 'final settlement', 'discharge billing'],
    steps: [
      { title: 'Add any last charges', text: 'Use “Add Charge” for final-day services.', visual: { button: 'Add Charge', icon: 'Plus', variant: 'primary' } },
      { title: 'Tick “Final discharge bill (whole stay)”', text: 'The dates lock to the whole stay. (After discharge this is automatic.)', visual: { fields: [{ label: 'Final discharge bill (whole stay)' }] } },
      { title: 'Collect the remaining amount', text: 'Payments Received → Add Payment until the balance is Fully Paid (or shows a credit).', visual: { button: 'Add Payment', icon: 'CreditCard', variant: 'primary' } },
      { title: 'Click “Print Bill”', text: 'The document is titled “Final Discharge Bill”.', visual: { button: 'Print Bill', icon: 'Printer', variant: 'primary' } },
    ],
    result: 'The patient receives the final bill; the account is settled so they can be discharged.',
    related: ['patient-discharge', 'ipd-balance'],
  },
  {
    id: 'ipd-corrections',
    category: 'ipd',
    requires: [P.billingView, 'adminOrAbove'],
    title: 'Correcting IPD charges and payments (Admin)',
    description: 'Edit or remove a charge, correct a payment — with a full audit trail.',
    when: 'When a charge or payment was entered wrongly.',
    keywords: ['edit charge', 'remove charge', 'correct payment', 'mistake', 'audit'],
    steps: [
      { title: 'Charges: pencil to edit, bin to remove', text: 'In Charges by Day. Editing keeps the charge number; removing moves it to the Trash.' },
      { title: 'Payments: pencil to correct, bin to remove', text: 'In Payments Received. The receipt number and date never change.', visual: { button: 'Save Correction', variant: 'primary' } },
    ],
    result: 'Totals update immediately. The audit log records who changed what, when, and the old and new values.',
    related: ['payment-wrong-amount', 'trash-restore'],
  },

  // ── Services ──────────────────────────────────────────────────────────────
  {
    id: 'services-view',
    category: 'services',
    requires: P.deptView,
    title: 'Browsing departments, services and prices',
    description: 'The service catalog used on bills.',
    when: 'To check a service’s price.',
    keywords: ['services', 'departments', 'price list', 'catalog', 'rates'],
    steps: [
      { title: 'Open Departments', text: 'Departments contain services (which may contain sub-services). Prices show in green.', visual: { nav: 'Departments' } },
      { title: 'Filter', text: '', visual: { chips: ['Active', 'Inactive', 'Priced', 'Needs Pricing'], active: [] } },
    ],
    result: 'You can see what each service costs.',
    related: ['services-manage', 'bill-add-items'],
    action: { label: 'Open Departments', to: '/admin/departments', requires: P.deptView },
  },
  {
    id: 'services-manage',
    category: 'services',
    requires: P.deptManage,
    title: 'Adding and pricing services',
    description: 'Create departments and services, set prices, deactivate.',
    when: 'When a new service is offered or a price changes.',
    keywords: ['add service', 'add department', 'price', 'deactivate service', 'needs pricing'],
    steps: [
      { title: 'Click “Add Department”', text: 'For a top-level department.', visual: { button: 'Add Department', icon: 'Plus', variant: 'primary' } },
      { title: 'Add a service inside it with “+”', text: 'Use the + (Add sub-item) on the department’s row.', visual: { button: 'Add sub-item', icon: 'Plus', variant: 'ghost' } },
      { title: 'Enter the details', text: 'Leave the price blank for a category that only groups other services.', visual: { fields: [{ label: 'Name', required: true }, { label: 'Price (₹)' }, { label: 'Description' }] } },
      { title: 'Edit later with the pencil', text: 'Change the price, or untick “Active” to stop it being billed.', visual: { button: 'Edit', icon: 'Pencil', variant: 'ghost' } },
    ],
    result: 'Priced, active services appear in Create Bill and in IPD “From service catalog”.',
    tips: ['“Needs Pricing” lists services that cannot be billed yet.', 'A department can only be deleted after its sub-items are removed.'],
    important: ['Changing a price does not change bills already issued.'],
    related: ['services-view'],
  },

  // ── Hospital settlement ───────────────────────────────────────────────────
  {
    id: 'settlement',
    category: 'settlement',
    requires: P.settlementView,
    title: 'How Hospital Settlement works',
    description: 'The daily hospital-covered amount for each admitted inpatient, and marking it collected.',
    when: 'When reconciling with partner hospitals.',
    keywords: ['settlement', 'hospital covered', 'daily rate', 'collected', 'pending', 'reconcile'],
    steps: [
      { title: 'Open Hospital Settlement', text: 'One entry is created per admitted inpatient per day, at the daily rate.', visual: { nav: 'Hospital Settlement' } },
      { title: 'Super Admin: set the daily rate', text: 'Under “Daily Hospital-Covered Rate”, enter the rate and click “Update Rate”.', visual: { button: 'Update Rate', variant: 'primary' } },
      { title: 'Mark entries collected', text: 'When the hospital pays, click “Mark Collected” on the entries (needs settlement manage access).', visual: { button: 'Mark Collected', variant: 'primary' } },
    ],
    result: 'Totals show Total Accrued, Collected and Pending.',
    tips: ['“Refresh” adds any missing days for admitted inpatients.'],
    related: ['dashboard-overview'],
    action: { label: 'Open Hospital Settlement', to: '/admin/hospital-settlement', requires: P.settlementView },
  },

  // ── Inquiries ─────────────────────────────────────────────────────────────
  {
    id: 'inquiries',
    category: 'inquiries',
    requires: P.inquiriesView,
    title: 'Handling website consultation requests and messages',
    description: 'Requests and messages sent from the public website, and job applications.',
    when: 'Several times a day — new requests show on the bell and the menu badge.',
    keywords: ['inquiry', 'booking', 'consultation request', 'appointment request', 'message', 'contact', 'job application', 'website'],
    steps: [
      { title: 'Open Inquiries', text: 'A red number on the menu shows how many are new.', visual: { nav: 'Inquiries' } },
      { title: 'Choose the tab', text: '', visual: { tabs: ['Consultations & Messages', 'Job Applications'], active: 'Consultations & Messages' } },
      { title: 'Call or email the person, then update the status', text: 'Use the status drop-down: new → contacted → closed (applications: new → reviewed → closed).' },
    ],
    result: 'Everyone who contacted the clinic is followed up, and the new count goes down.',
    tips: ['Consultation requests are how patients ask for an appointment online — call them to arrange the visit, then register them as a patient.', 'Spam or junk submissions can be removed with the bin on the row (if you can manage inquiries). This cannot be undone.'],
    related: ['patient-add'],
    action: { label: 'Open Inquiries', to: '/admin/inquiries', requires: P.inquiriesView },
  },

  // ── Staff ─────────────────────────────────────────────────────────────────
  {
    id: 'users-add',
    category: 'staff',
    requires: 'superadmin',
    title: 'How to add a staff member (Admin, Receptionist, Therapist)',
    description: 'Create a login — the person gets an email to set their own password.',
    when: 'When someone joins.',
    keywords: ['add user', 'new staff', 'create account', 'receptionist', 'admin', 'therapist login', 'invite', 'department', 'therapist department', 'phone', 'qualification', 'address'],
    steps: [
      { title: 'Open User Management', text: '', visual: { nav: 'User Management' } },
      { title: 'Click “Add User”', text: '', visual: { button: 'Add User', icon: 'UserPlus', variant: 'primary' } },
      { title: 'Enter name, email, role and phone', text: 'Phone is required for everyone; Address is optional. For a therapist the form also asks for their Qualification (optional). Optionally tick Permission Overrides to give this person extra access on top of their role (e.g. let a Therapist onboard patients). Unticked boxes simply use the role’s default access.', visual: { fields: [{ label: 'Full Name', required: true }, { label: 'Email', required: true }, { label: 'Role', required: true }, { label: 'Phone', required: true }, { label: 'Qualification' }, { label: 'Address' }, { label: 'Permission Overrides' }] } },
      { title: 'For a therapist, tick their departments', text: 'When Role is Therapist, Departments shows every department as a tick-box — tick all that apply. They decide which bills the therapist can see, and are copied to Settings › Therapists automatically.', visual: { chips: ['Physiotherapy', 'Occupational Therapy'], active: ['Physiotherapy', 'Occupational Therapy'] } },
      { title: 'Click “Create Account”', text: 'A set-password email is sent. “Send set-password email” resends it.', visual: { button: 'Create Account', variant: 'primary' } },
    ],
    result: 'The person can sign in once they set their password. A therapist also appears in Settings › Therapists with the phone, qualification, address and departments you entered — these print as the physician’s details on bills.',
    related: ['users-manage', 'settings-therapists', 'users-requests'],
    action: { label: 'Open User Management', to: '/admin/users', requires: 'superadmin' },
  },
  {
    id: 'users-manage',
    category: 'staff',
    requires: 'superadmin',
    title: 'Changing roles and permissions, deactivating or removing staff',
    description: 'Edit a staff member’s role and access, block access, or move them to the Trash.',
    when: 'When responsibilities change, or someone leaves.',
    keywords: ['permissions', 'role', 'deactivate', 'reactivate', 'delete user', 'remove staff', 'access'],
    steps: [
      { title: 'Edit details, role, departments and access', text: 'Click “Edit”, change the phone, address, Role, a therapist’s Qualification and Departments (tick-boxes), or Permission Overrides, and click “Save Changes”. Older accounts without a phone number must have one added before saving.', visual: { button: 'Edit', icon: 'Pencil', variant: 'ghost' } },
      { title: 'Temporarily block access', text: '“Deactivate” signs them out and blocks everything; “Reactivate” restores it.', visual: { button: 'Deactivate', variant: 'ghost' } },
      { title: 'Remove someone who has left', text: '“Move to Trash” (type to confirm). They can be restored from Trash › Staff.', visual: { button: 'Move to Trash', icon: 'Trash2', variant: 'danger' } },
    ],
    result: 'Access changes take effect immediately.',
    important: ['Records they created (bills, payments, sessions) are kept.', 'A ticked Permission Override adds access on top of the role; unticking it returns them to the role’s default access. Some actions stay role-only whatever is ticked — editing or trashing bills and correcting payments (Admin and above), and Trash, Settings and creating staff (Super Admin).'],
    related: ['gs-my-access', 'trash-restore'],
  },
  {
    id: 'users-requests',
    category: 'staff',
    requires: 'superadmin',
    title: 'Approving account requests',
    description: 'Pending requests for a staff account.',
    when: 'When the bell shows an account request.',
    keywords: ['account request', 'approve', 'dismiss', 'pending'],
    steps: [
      { title: 'Open User Management', text: '“Pending Account Requests” appears at the top when there are any.', visual: { nav: 'User Management' } },
      { title: 'Approve or Dismiss', text: '“Approve” opens Add User pre-filled — choose the role and click “Create Account”.', visual: { button: 'Approve', icon: 'UserCheck', variant: 'primary' } },
    ],
    result: 'The person receives a set-password email.',
    related: ['users-add'],
  },
  {
    id: 'users-view',
    category: 'staff',
    requires: P.usersView,
    title: 'Viewing the staff list',
    description: 'A read-only list of staff accounts.',
    when: 'To find a colleague’s role or email.',
    keywords: ['staff list', 'users', 'colleagues'],
    steps: [{ title: 'Open User Management', text: 'Filter by role or status. Only the Super Admin can make changes.', visual: { nav: 'User Management' } }],
    result: 'You can see who has which role.',
    related: ['gs-my-access'],
  },

  // ── Settings ──────────────────────────────────────────────────────────────
  {
    id: 'settings-hospitals',
    category: 'settings',
    requires: 'superadmin',
    title: 'Setting up hospitals (bill branding)',
    description: 'Partner hospitals — each bill and receipt is branded with one.',
    when: 'During first setup, and when you partner with a new hospital.',
    keywords: ['hospital', 'logo', 'branding', 'partner hospital', 'address', 'setup'],
    steps: [
      { title: 'Open Settings › Hospitals', text: '', visual: { tabs: ['Hospitals', 'Therapists', 'Bill Settings'], active: 'Hospitals' } },
      { title: 'Click “Add Hospital”', text: 'First time? “Add AArambh (pre-filled)” fills in your details — check the address and phone.', visual: { button: 'Add Hospital', icon: 'Plus', variant: 'primary' } },
      { title: 'Fill in the details and upload the logo', text: 'Name, logo, address lines, phone, email, website, footer lines (up to 4) and the default bill note. Untick Active to hide it from new bills.' },
      { title: 'Click “Save Hospital”', text: '', visual: { button: 'Save Hospital', variant: 'primary' } },
    ],
    result: 'The hospital can be chosen on bills and appears in the patient registration drop-down.',
    related: ['settings-bill', 'settings-hospital-delete', 'patient-add'],
    action: { label: 'Open Settings', to: '/admin/settings', requires: 'superadmin' },
  },
  {
    id: 'settings-hospital-delete',
    category: 'settings',
    requires: 'superadmin',
    title: 'Deleting a hospital',
    description: 'Permanently delete a hospital entry — bills already issued are kept.',
    when: 'Only when a partnership has ended and the hospital will never be used again (otherwise untick Active).',
    keywords: ['delete hospital', 'remove hospital'],
    steps: [
      { title: 'Click the bin on the hospital’s card', text: '', visual: { button: 'Delete hospital', icon: 'Trash2', variant: 'danger' } },
      { title: 'Read what will happen, type the hospital name, and click “Delete Hospital”', text: 'The dialog shows how many bills were issued under it.', visual: { button: 'Delete Hospital', variant: 'danger' } },
    ],
    result: 'The hospital is removed. Its bills stay in patients’ records with the hospital’s name and address, but without its logo.',
    important: ['This cannot be undone. Unticking “Active” is usually the better choice.'],
    related: ['settings-hospitals'],
  },
  {
    id: 'settings-therapists',
    category: 'settings',
    requires: 'superadmin',
    title: 'Managing therapists (physicians on bills)',
    description: 'Therapists are chosen as the prescribing physician and assigned to patients.',
    when: 'When a therapist joins, or their departments change.',
    keywords: ['therapist', 'physician', 'departments', 'import', 'doctor'],
    steps: [
      { title: 'Open Settings › Therapists', text: '', visual: { tabs: ['Hospitals', 'Therapists', 'Bill Settings'], active: 'Therapists' } },
      { title: 'Import staff logins', text: '“Import N therapist logins” creates entries for therapists who already have a login.', visual: { button: 'Import therapist logins', icon: 'Download', variant: 'ghost' } },
      { title: 'Or click “Add Therapist”', text: 'Name, qualification, phone, address, the staff login to link, and their departments.', visual: { button: 'Add Therapist', icon: 'Plus', variant: 'primary' } },
      { title: 'Tick their departments', text: 'A therapist sees bills that contain services from their departments. Departments, phone, address and qualification are the same as in User Management — changing them in either place updates both.' },
    ],
    result: 'The therapist appears in the physician list on bills and in Assigned Therapists on patients.',
    related: ['settings-therapist-delete', 'therapist-assigned', 'users-add'],
  },
  {
    id: 'settings-therapist-delete',
    category: 'settings',
    requires: 'superadmin',
    title: 'Deleting a therapist',
    description: 'Remove a therapist entry while keeping their history.',
    when: 'When a therapist leaves.',
    keywords: ['delete therapist', 'remove therapist', 'therapist left'],
    steps: [
      { title: 'Click the bin on the therapist’s row', text: '', visual: { button: 'Delete therapist', icon: 'Trash2', variant: 'danger' } },
      { title: 'Review, type their name, and click “Delete Therapist”', text: 'The option to also remove their staff login is ticked by default.', visual: { button: 'Delete Therapist', variant: 'danger' } },
    ],
    result: 'They are unassigned from patients and leave the physician list. Bills they created or were physician on, session logs and payments keep their name.',
    related: ['settings-therapists', 'users-manage'],
  },
  {
    id: 'settings-bill',
    category: 'settings',
    requires: 'superadmin',
    title: 'Bill settings: your own hospital and the tax %',
    description: 'Which hospital brands direct patients’ bills, and the tax on every new bill.',
    when: 'During setup, or when the tax rate changes.',
    keywords: ['tax', 'gst', 'own hospital', 'bill settings', 'default hospital'],
    steps: [
      { title: 'Open Settings › Bill Settings', text: '', visual: { tabs: ['Hospitals', 'Therapists', 'Bill Settings'], active: 'Bill Settings' } },
      { title: 'Your own hospital', text: 'Brands bills and receipts for Out Patient, Home Visit and Virtual patients. It saves as soon as you choose.', visual: { fields: [{ label: 'Your own hospital' }] } },
      { title: 'Tax on bills', text: 'Enter the percentage and click “Save”. Applied to every new bill on the amount after discount.', visual: { button: 'Save', icon: 'Save', variant: 'primary' } },
    ],
    result: 'New bills use these settings automatically; issued bills are unchanged.',
    related: ['bill-tax', 'settings-hospitals'],
  },

  // ── Trash ─────────────────────────────────────────────────────────────────
  {
    id: 'trash-restore',
    category: 'trash',
    requires: 'superadmin',
    title: 'Restoring something from the Trash',
    description: 'Deleted patients, bills/payments and staff can be brought back — unless they were deleted permanently.',
    when: 'When something was deleted by mistake.',
    keywords: ['trash', 'restore', 'undo delete', 'recover', 'deleted'],
    steps: [
      { title: 'Open Trash', text: '', visual: { nav: 'Trash' } },
      { title: 'Choose the tab and click “Restore”', text: 'A bill of a patient who is also in the Trash can only be restored after the patient.', visual: { tabs: ['Patients', 'Bills', 'Staff'], active: 'Bills' } },
    ],
    result: 'It returns exactly as it was, and totals and balances include it again.',
    related: ['trash-delete', 'patient-trash', 'bill-correct', 'users-manage'],
    action: { label: 'Open Trash', to: '/admin/trash', requires: 'superadmin' },
  },

  {
    id: 'trash-delete',
    category: 'trash',
    requires: 'superadmin',
    title: 'Deleting permanently from the Trash',
    description: 'Erase a patient, bill/payment or staff account for good.',
    when: 'Only for records that must never come back (for example a duplicate patient). Otherwise leave it in the Trash — it does not count anywhere.',
    keywords: ['delete permanently', 'erase', 'remove forever', 'empty trash', 'permanent delete'],
    steps: [
      { title: 'Open Trash and choose the tab', text: '', visual: { tabs: ['Patients', 'Bills', 'Staff'], active: 'Patients' } },
      { title: 'Click “Delete” on the row', text: 'It is next to “Restore”.', visual: { button: 'Delete', icon: 'Trash2', variant: 'danger' } },
      { title: 'Read what will be removed, type the confirmation and click “Delete Permanently”', text: 'For a patient the dialog counts their visits, charges, payments, bills, session logs and settlement entries — all of them are deleted with the patient. Type the patient’s name (a bill: its amount; staff: their email).', visual: { button: 'Delete Permanently', variant: 'danger' } },
    ],
    result: 'The item is gone for good and cannot be restored. An entry recording what was deleted, by whom and when is kept in the audit log.',
    important: ['This cannot be undone.', 'A permanently deleted staff member’s email cannot be used for a new staff account — restore instead if they may return.'],
    related: ['trash-restore'],
    action: { label: 'Open Trash', to: '/admin/trash', requires: 'superadmin' },
  },

  // ── Printing ──────────────────────────────────────────────────────────────
  {
    id: 'printing-tips',
    category: 'printing',
    requires: [P.billsView],
    title: 'Printing tips (A4, colours, PDF)',
    description: 'Get clean prints of bills, receipts and IPD bills.',
    when: 'Before printing for the first time on a new computer.',
    keywords: ['print', 'printer', 'a4', 'pdf', 'colour', 'margins', 'save as pdf'],
    steps: [
      { title: 'Use the print button in the app', text: '“Print Invoice”, “Print Receipt” or “Print Bill”. The app prints only the document, never the menu.', visual: { button: 'Print Invoice', icon: 'Printer', variant: 'primary' } },
      { title: 'Paper size A4', text: 'In the print window choose A4 paper.' },
      { title: 'To save a file, choose “Save as PDF”', text: 'Set Destination/Printer to “Save as PDF”, then Save.' },
    ],
    result: 'A clean, correctly sized document.',
    tips: ['If colours or the blue header are missing, turn on “Background graphics” in the print window’s “More settings”.', 'Leave scale at 100% (Default).'],
    related: ['bill-print', 'receipt-print', 'ipd-print', 'trouble-print'],
  },

  // ── Troubleshooting ───────────────────────────────────────────────────────
  {
    id: 'trouble-cant-find-patient',
    category: 'troubleshooting',
    requires: P.patientsView,
    title: 'I cannot find a patient',
    description: 'The search or list does not show the patient you expect.',
    keywords: ['cannot find', 'not found', 'missing patient', 'search not working'],
    fixes: [
      { cause: 'The patient is discharged and the list shows only “Active”.', solution: 'Choose the “All” or “Discharged” filter.' },
      { cause: 'Searching by the middle of a name.', solution: 'Type the beginning of the name, the patient code, or the full phone number.' },
      { cause: 'The patient was moved to the Trash.', solution: 'Ask your Super Admin to check Trash › Patients.', needsAdmin: true },
      { cause: 'The patient was never registered.', solution: 'Register them with “Add Patient”.' },
    ],
    related: ['patient-search', 'patient-add'],
  },
  {
    id: 'trouble-cant-create-bill',
    category: 'troubleshooting',
    requires: P.billsCreate,
    title: 'I cannot create or save a bill',
    description: 'The bill will not save, or the Save Bill button is disabled.',
    keywords: ['cannot save', 'save disabled', 'bill error', 'select a hospital', 'no hospital'],
    fixes: [
      { cause: '“Select a patient.” / “Select a hospital.” / “Add at least one item.”', solution: 'Fill in the missing part — the message tells you which.' },
      { cause: 'No hospitals set up yet.', solution: 'Ask your Super Admin to add one in Settings › Hospitals.', needsAdmin: true },
      { cause: '“Every item needs a valid price.”', solution: 'Give each line a price of 0 or more.' },
      { cause: 'Save is briefly disabled while bill settings load.', solution: 'Wait a second; if it stays disabled, reload the page.' },
      { cause: 'The service you need does not appear.', solution: 'It has no price or is inactive — use “Custom item”, or ask the Super Admin to price it.' },
    ],
    related: ['bill-create', 'trouble-save-disabled'],
  },
  {
    id: 'trouble-save-disabled',
    category: 'troubleshooting',
    title: 'The Save / Delete button is disabled',
    description: 'Why a button is greyed out.',
    keywords: ['disabled', 'greyed out', 'cannot click', 'button not working'],
    fixes: [
      { cause: 'A required field (marked *) is empty.', solution: 'Fill in every required field.' },
      { cause: 'A delete confirmation needs the exact text.', solution: 'Type the phrase exactly as shown (capital letters included).' },
      { cause: 'Discharge with pending dues.', solution: 'Settle the balance first.' },
      { cause: 'It is already saving.', solution: 'Wait for it to finish — clicking twice is prevented on purpose.' },
    ],
    related: ['trouble-cant-discharge'],
  },
  {
    id: 'trouble-cant-discharge',
    category: 'troubleshooting',
    requires: P.patientsView,
    title: 'I cannot discharge a patient',
    description: 'The Discharge / Mark Inactive button is missing or disabled.',
    keywords: ['cannot discharge', 'discharge disabled', 'pending dues'],
    fixes: [
      { cause: 'The patient has pending dues.', solution: 'Record the remaining payment until the balance is zero or in credit.' },
      { cause: 'Your role cannot discharge (receptionists by default).', solution: 'Ask an Admin, or your Super Admin to grant “Discharge / close an encounter”.', needsAdmin: true },
    ],
    related: ['patient-discharge', 'payment-record'],
  },
  {
    id: 'trouble-print',
    category: 'troubleshooting',
    requires: P.billsView,
    title: 'I cannot print, or the PDF looks wrong',
    description: 'Blank pages, missing colours, wrong size.',
    keywords: ['print not working', 'pdf wrong', 'blank', 'colours missing', 'cut off'],
    fixes: [
      { cause: 'Colours/blue header missing.', solution: 'In the print window, More settings → tick “Background graphics”.' },
      { cause: 'Wrong size or cut off.', solution: 'Choose A4 paper and scale “Default” (100%).' },
      { cause: 'Printing from the browser menu on another page.', solution: 'Open the bill/receipt first and use its Print button.' },
      { cause: 'No printer connected.', solution: 'Choose “Save as PDF” and print the file later.' },
    ],
    related: ['printing-tips'],
  },
  {
    id: 'trouble-cant-see-menu',
    category: 'troubleshooting',
    title: 'I cannot see a menu item or open a feature',
    description: 'A page or button that colleagues have is missing for you.',
    keywords: ['missing menu', 'no access', 'permission denied', 'cannot access', 'feature missing'],
    fixes: [
      { cause: 'Your role does not include it.', solution: 'See “What can I do with my account?”. Ask your Super Admin if you need it.', needsAdmin: true },
      { cause: 'On a phone the menu is hidden.', solution: 'Tap ☰ at the top-left.' },
      { cause: '“You don’t have permission to do this.”', solution: 'The server blocked it for your role — contact your administrator.', needsAdmin: true },
    ],
    related: ['gs-my-access', 'gs-navigation'],
  },
  {
    id: 'trouble-not-loading',
    category: 'troubleshooting',
    title: 'The page is not loading',
    description: 'Stuck on “Loading…”, or an error.',
    keywords: ['not loading', 'slow', 'stuck', 'error', 'blank page', 'offline'],
    fixes: [
      { cause: 'Internet connection dropped.', solution: 'Check the connection and reload the page.' },
      { cause: 'The app was updated while it was open.', solution: 'Reload the page (Ctrl+R, or pull down on a phone).' },
      { cause: 'Still not working.', solution: 'Sign out and in again; if it persists, contact your administrator.', needsAdmin: true },
    ],
    related: ['trouble-cant-sign-in'],
  },
  {
    id: 'trouble-cant-sign-in',
    category: 'troubleshooting',
    title: 'I cannot sign in',
    description: 'Wrong password, deactivated account, or no email.',
    keywords: ['cannot login', 'wrong password', 'locked', 'deactivated', 'sign in error'],
    fixes: [
      { cause: 'Forgotten password.', solution: 'Type your email, click “Forgot password?”, and use the emailed link.' },
      { cause: '“Your account has been deactivated” / “no longer has access”.', solution: 'Contact your Super Admin.', needsAdmin: true },
      { cause: 'Reset email not arriving.', solution: 'Check spam/junk, and that the email is the one registered for you.' },
    ],
    related: ['gs-sign-in'],
  },
  {
    id: 'trouble-therapist-bill',
    category: 'troubleshooting',
    audience: ['therapist'],
    title: 'I cannot see a patient’s bill',
    description: 'Therapists only see some bills.',
    keywords: ['cannot see bill', 'bill missing', 'therapist bill'],
    fixes: [
      { cause: 'You are not assigned to the patient and the bill has no services from your departments.', solution: 'Ask a receptionist/admin to add you under Assigned Therapists on the patient.' },
      { cause: 'Your departments are not set.', solution: 'Ask your Super Admin to set them in Settings › Therapists.', needsAdmin: true },
    ],
    related: ['therapist-assigned'],
  },
];

// Step-by-step processes shown as timelines. Each step may link to an article.
export const WORKFLOWS = [
  {
    id: 'new-outpatient',
    title: 'A new out-patient visit, start to finish',
    description: 'Registration to receipt for an Out Patient, Home Visit or Virtual patient.',
    requires: P.patientsCreate,
    steps: [
      { title: 'Register the patient', text: 'Patients → Add Patient. Choose Out Patient, Home Visit or Virtual.', article: 'patient-add' },
      { title: 'Take an advance (optional)', text: 'Enter it on the form — receipt R0001 is created.', article: 'payment-advance' },
      { title: 'Therapy session', text: 'The therapist adds a Treatment Progress entry on the profile.', article: 'session-log-add' },
      { title: 'Create the bill', text: 'Profile → Create Bill, add the services, Save Bill.', article: 'bill-create' },
      { title: 'Print the bill', text: 'Print Invoice (optional).', article: 'bill-print' },
      { title: 'Receive payment', text: 'Profile → Record Payment.', article: 'payment-record' },
      { title: 'Print the receipt', text: 'View & Print Receipt.', article: 'receipt-print' },
      { title: 'Close the visit', text: 'When treatment ends and dues are clear: Mark Inactive (Admin).', article: 'patient-discharge' },
    ],
  },
  {
    id: 'ipd-stay',
    title: 'IPD: admission to discharge',
    description: 'An inpatient stay with a running bill.',
    requires: P.billingView,
    steps: [
      { title: 'Register / admit', text: 'Choose the referring hospital as “Received from” — or Readmit as Inpatient.', article: 'ipd-admit' },
      { title: 'Open the IPD running bill', text: 'Billing → IPD / Hospital Running Bill → patient → admission.', article: 'ipd-open' },
      { title: 'Ward, room & doctor', text: 'Record the admission details.', article: 'ipd-admission-details' },
      { title: 'Advance at admission', text: 'Payments Received → Add Payment.', article: 'ipd-interim-payment' },
      { title: 'Add charges during the stay', text: 'Add Charge — room rent with “Repeat daily until”.', article: 'ipd-add-charges' },
      { title: 'Interim payments', text: 'Each payment gets its own receipt.', article: 'ipd-interim-payment' },
      { title: 'Review the running balance', text: 'Totals, period, Account Ledger; print an interim bill if asked.', article: 'ipd-balance' },
      { title: 'Final discharge bill', text: 'Add final charges, tick “Final discharge bill”, Print Bill.', article: 'ipd-final-bill' },
      { title: 'Receive the remaining amount', text: 'Until Fully Paid.', article: 'payment-record' },
      { title: 'Discharge', text: 'Profile → Discharge (Admin).', article: 'patient-discharge' },
    ],
  },
  {
    id: 'therapist-day',
    title: 'A therapist’s day',
    description: 'From sign-in to logging every session.',
    audience: ['therapist'],
    steps: [
      { title: 'Sign in and check the Dashboard', text: 'See today’s sessions and active patients.', article: 'dashboard-overview' },
      { title: 'Open each patient', text: 'Patients → search → open the profile; read the history.', article: 'patient-profile' },
      { title: 'Record the session', text: 'Treatment Progress → Add Entry.', article: 'session-log-add' },
      { title: 'Check your day', text: 'Therapy Sessions → “Logged by me”.', article: 'sessions-page' },
    ],
  },
  {
    id: 'superadmin-setup',
    title: 'First-time setup (Super Admin)',
    description: 'Everything to set up before staff start billing.',
    requires: 'superadmin',
    steps: [
      { title: 'Add hospitals', text: 'Settings › Hospitals — your own (AArambh) and partners, with logos.', article: 'settings-hospitals' },
      { title: 'Bill settings', text: 'Your own hospital and the tax %.', article: 'settings-bill' },
      { title: 'Price your services', text: 'Departments — fix everything under “Needs Pricing”.', article: 'services-manage' },
      { title: 'Add staff', text: 'User Management → Add User for each person.', article: 'users-add' },
      { title: 'Set up therapists', text: 'Settings › Therapists → import logins, tick departments.', article: 'settings-therapists' },
      { title: 'Hospital settlement rate', text: 'If partner hospitals pay a daily rate for inpatients.', article: 'settlement' },
    ],
  },
];

export const FAQS = [
  { q: 'Can I install this as an app on my computer or phone?', a: 'Yes. Click “Install app” in the top bar. It works on Windows and Mac (Chrome or Edge) and on Android; on iPhone/iPad use Safari’s Share → “Add to Home Screen”.', article: 'gs-install-app' },
  { q: 'How do I add a patient?', a: 'Patients → Add Patient → fill in the form → Create Patient.', article: 'patient-add', requires: P.patientsCreate },
  { q: 'How do I find an old patient?', a: 'Search by patient code, the start of the name, or phone number — and choose “All” to include discharged patients.', article: 'patient-search', requires: P.patientsView },
  { q: 'Where do I book appointments?', a: 'The app does not have an appointment calendar. Appointment requests from the website arrive in Inquiries as “Consultation Requests”; call the person to arrange the visit, then register them as a patient.', article: 'inquiries', requires: P.inquiriesView },
  { q: 'Where can I see today’s sessions?', a: 'Dashboard › Therapy Sessions, or the Therapy Sessions page with “Today”.', article: 'sessions-page', requires: P.sessionsView },
  { q: 'How do I print a bill?', a: 'Open the bill → Print Invoice. For a PDF, choose “Save as PDF” in the print window.', article: 'bill-print', requires: P.billsView },
  { q: 'How do I record a payment?', a: 'Patient profile → Patient Balance → Record Payment. A receipt number is created automatically.', article: 'payment-record', requires: P.recordPayment },
  { q: 'How do I admit a patient?', a: 'Register them choosing the referring hospital (Inpatient), or Readmit a discharged patient as Inpatient.', article: 'ipd-admit', requires: P.patientsCreate },
  { q: 'How do I generate an IPD running bill?', a: 'Billing → IPD / Hospital Running Bill → choose the patient and admission → Print Bill.', article: 'ipd-open', requires: P.billingView },
  { q: 'What should I do if I entered the wrong amount?', a: 'Tell an Admin. Admins correct IPD payments directly, or move a wrong payment to the Trash and record it again. Everything is logged.', article: 'payment-wrong-amount', requires: P.billingView },
  { q: 'What if I cannot find a patient?', a: 'Check the Active/All filter, search by code or phone, or ask the Super Admin to check the Trash.', article: 'trouble-cant-find-patient', requires: P.patientsView },
  { q: 'Why can’t I access a particular feature?', a: 'Your role does not include it. See “What can I do with my account?” and ask your Super Admin if you need it.', article: 'gs-my-access' },
  { q: 'Is there a Reports page?', a: 'Not a separate one. The Dashboard figures, and Billing › Transactions with its date and type filters, give the totals.', article: 'transactions', requires: P.billingView },
  { q: 'Why is the tax on my bill different from last month?', a: 'The Super Admin sets one tax % for new bills. Bills already issued keep the tax they were created with.', article: 'bill-tax', requires: P.billsView },
  { q: 'How do I print a receipt for an old payment?', a: 'Patient profile → Transaction History → “Receipt” next to the payment.', article: 'receipt-print', requires: P.billingView },
];
